#!/usr/bin/bash
set -e
set -u

# parse ~/.config/FlatColor-16/colors.css and extract colors
LINES="$(cat ~/.config/FlatColor-16/colors.css \
    | sed -n 's/@define-color \(base[0-9]\{2\}\) \(#[0-9A-Fa-f]\{6\}\);/\1 \2/p')"

declare -A colors
while read -r line; do
    read -a words <<< "$line"
    colors["${words[0]}"]="${words[1]}"
done <<< "$LINES"

# Assemble gitrc file
GTKRC_HEADER="\
# This file was automatically generated by
# ~/.themes/FlatColor/update-gtk2-theme.sh.
# To change this file, change gtkrc.template
# instead and then run the aforementioned
# script to propagate the changes to this file."

GTK_COLOR_SCHEME_TEMPLATE="\
gtk-color-scheme = \"bg_color:%base00%
text_color:%base05%
selected_bg_color:%base02%
selected_fg_color:%base05%
tooltip_bg_color:%base00%
tooltip_fg_color:%base05%
titlebar_bg_color:%base00%
titlebar_fg_color:%base05%
menu_bg_color:%base00%
menu_fg_color:%base05%
link_color:%base02%\""

GTK_COLOR_SCHEME="$(
    echo "$GTK_COLOR_SCHEME_TEMPLATE" | sed \
        -e "s/%base00%/${colors[base00]}/" \
        -e "s/%base02%/${colors[base02]}/" \
        -e "s/%base05%/${colors[base05]}/" \
)"

cat <(echo "$GTKRC_HEADER") \
    <(echo) \
    <(echo "$GTK_COLOR_SCHEME") \
    <(echo) \
    gtk-2.0/gtkrc.template \
    > gtk-2.0/gtkrc

chmod -w gtk-2.0/gtkrc
